=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article-segmented/batch_desnews/articles/article.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<!--root element, represents a single article, possibly spanning multiple pages-->
<!ELEMENT article (header-item*, article-page+)>
<!--unit-href: A relative path to the containing unit's xml-->
<!--classification: The article classification-->
<!ATTLIST article
	unit-href CDATA #REQUIRED
	classification CDATA #IMPLIED
	xmlns CDATA #FIXED "http://www.iarchives.com/schema/2002/export"
>
<!--For a unit, these are all the articles contained in this unit.  For a page, these are all the articles which *begin* on the page.-->
<!ELEMENT articles (article-ref*)>
<!--This is the meta-data associated with the scope.  It might include date, edition, section,  page, article name, etc.-->
<!ELEMENT header-item (#PCDATA)>
<!--name: The type of data contained in the element (date, edition, section)-->
<!ATTLIST header-item
	name CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!--A sequence of word nodes-->
<!ELEMENT nodes (n*)>
<!--A page the article appears on.-->
<!ELEMENT article-page (article-clipping+)>
<!--href: A relative path to the page xml file for this page of the article-->
<!ATTLIST article-page
	href CDATA #REQUIRED
>
<!--A reference to an article-->
<!ELEMENT article-ref EMPTY>
<!--href: A relative path to the xml describing this article-->
<!ATTLIST article-ref
	href CDATA #REQUIRED
>
<!--Node Element.  Represents one or more word options at a given location.  Element and attribute names are abbreviated to save space, since there will be many of these elements.-->
<!ELEMENT n (r*, o+)>
<!--i: the node's ID.  Note that these ID's are not global.  They are local to the enclosing nodes element.-->
<!--n: A comma-separated list of next-node IDs.  The OCR tries to order the words in reading order, and this is the way that is represented.  Multiple next-nodes occur when multiple OCR engines disagree on which word should follow.  -->
<!ATTLIST n
	i CDATA #REQUIRED
	n CDATA #IMPLIED
>
<!--Represents an image that contains a section of the article.  The coordinates refer to the the containing page's image.-->
<!ELEMENT article-clipping (article-element+)>
<!--image-file: specifies the relative location of the file containing the article clipping-->
<!--index: A zero-based index into the image file, if the image is a multi-page tif, for example.  -->
<!--l: The left coordinate-->
<!--t: The top coordinate-->
<!--r: The right coordinate-->
<!--b: The bottom coordinate-->
<!ATTLIST article-clipping
	image-file CDATA #REQUIRED
	index CDATA #IMPLIED
	l CDATA #REQUIRED
	t CDATA #REQUIRED
	r CDATA #REQUIRED
	b CDATA #REQUIRED
>
<!--Node rectangle.  Nodes may have more than one rectangle ( if the word is hyphenated, for example).  If the exported images is PDF only, word coordinates are not needed, and there will be no rectangle node.-->
<!ELEMENT r EMPTY>
<!--l: The left coordinate-->
<!--t: The top coordinate-->
<!--r: The right coordinate-->
<!--b: The bottom coordinate-->
<!ATTLIST r
	l CDATA #REQUIRED
	t CDATA #REQUIRED
	r CDATA #REQUIRED
	b CDATA #REQUIRED
>
<!--Word option element.  The text of this element is the word.-->
<!ELEMENT o (#PCDATA)>
<!--p: The pdf character offset
This is the character offset that marks the beginning of the word on the corresponding pdf page.  It facilitates pdf word highlighting, and corresponds to the "pos" attribute in the pdf Highlight Format's "loc" tag.-->
<!ATTLIST o
	p CDATA #IMPLIED
>
<!--An article element represents an even smaller section of the article, such as the headline, the byline or the body.-->
<!ELEMENT article-element (text?, zone*)>
<!--type: Specifies whether it is a headline, subheadline, byline, body, etc.-->
<!ATTLIST article-element
	type CDATA #REQUIRED
>
<!--The text of the article-element.  In most cases, this will simply be a concatenation of the zone-text from each zone.-->
<!ELEMENT text (#PCDATA)>
<!--A rectangular region in the article element.  The coordinates of this zone refer to the the article's image (the image specified in the article-clipping element).-->
<!ELEMENT zone (zone-text?, nodes?)>
<!--l: The left coordinate-->
<!--t: The top coordinate-->
<!--r: The right coordinate-->
<!--b: The bottom coordinate-->
<!ATTLIST zone
	l CDATA #REQUIRED
	t CDATA #REQUIRED
	r CDATA #REQUIRED
	b CDATA #REQUIRED
>
<!--The text contained in the particular zone.  Usually a substring of the article element's text element.-->
<!ELEMENT zone-text (#PCDATA)>

=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article-segmented/batch_desnews/articles/0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article SYSTEM "article.dtd">
<article xmlns="http://www.iarchives.com/schema/2002/export" unit-href="../unit.xml" classification="unclassified"><header-item name="volume" value="1">I</header-item><header-item name="number" value="1">1</header-item><header-item name="date" value="675867">15-JUN-1850</header-item><header-item name="page" value="1">1</header-item><article-page href="../pages/p001_Va_071_D45_v01.xml"><article-clipping image-file="pdf/0.pdf" index="0" l="0" t="0" r="1407" b="390"><article-element type="article"><zone l="0" t="0" r="1407" b="240"><nodes><n i="Oc"><o p="0">D</o></n><n i="Od"><o p="1">S</o></n><n i="Oe"><o p="2">ERET</o></n><n i="Of"><o p="6">E</o></n><n i="Og"><o p="7">BY</o><o p="9">HY</o></n><n i="BS"><o p="11">W</o></n><n i="BT"><o p="12">RICHARDS</o></n><n i="BU"><o p="20">tx</o></n><n i="BV"><o p="22">S</o></n><n i="Oh"><o p="23">L</o></n><n i="BW"><o p="24">I</o><o p="25">1</o></n><n i="BX"><o p="26">CITY</o></n><n i="BY"><o p="30">DESERET</o></n><n i="BZ"><o p="37">1</o></n><n i="Ba"><o p="38">JUNE</o></n><n i="Bb"><o p="42">15</o></n><n i="Bc"><o p="44">ysae</o></n><n i="Bd"><o p="48">VOL</o></n><n i="Be"><o p="51">1</o></n><n i="Oi"><o p="52">NO</o></n><n i="Bf"><o p="54">0</o></n><n i="Bg"><o p="55">1</o></n></nodes></zone></article-element><article-element type="article"><zone l="0" t="239" r="454" b="390"><nodes><n i="Bh"><o p="56">LAT</o></n><n i="Bi"><o p="59">40</o></n><n i="Bj"><o p="61">45</o></n><n i="Bk"><o p="63">44</o></n><n i="Bl"><o p="65">LON</o></n><n i="S"><o p="68">I</o><o p="69">1</o></n><n i="Bm"><o p="70">ill</o><o p="73">iii</o></n><n i="T"><o p="76">I</o><o p="77">1</o></n><n i="U"><o p="78">1</o></n><n i="Bn"><o p="79">26</o><o p="81">06</o></n><n i="Bo"><o p="83">34</o></n><n i="Bp"><o p="85">prospectus</o></n><n i="Bq"><o p="95">DESERET</o></n><n i="Br"><o p="102">NEWS</o></n></nodes></zone></article-element></article-clipping></article-page></article>

=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article-segmented/batch_deseret_news/articles/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article SYSTEM "article.dtd">
<article xmlns="http://www.iarchives.com/schema/2002/export" unit-href="../unit.xml" classification="unclassified"><header-item name="volume" value="1">I</header-item><header-item name="number" value="1">1</header-item><header-item name="date" value="675867">15-JUN-1850</header-item><header-item name="page" value="4">4</header-item><article-page href="../pages/p004_Va_071_D45_v01.xml"><article-clipping image-file="pdf/6.pdf" index="0" l="0" t="909" r="498" b="1002"><article-element type="article"><zone l="0" t="0" r="498" b="93"><nodes><n i="C+"><o p="0">bield</o></n><n i="S3"><o p="5">1</o></n><n i="S4"><o p="6">E</o></n><n i="S5"><o p="7">ISE</o></n><n i="S6"><o p="10">R</o></n><n i="S7"><o p="11">ET</o></n><n i="Im"><o p="13">jlewis</o></n><n i="S8"><o p="19">A</o></n><n i="S9"><o p="20">E</o></n><n i="S+"><o p="21">W</o></n><n i="A"><o p="22">lyl</o><o p="25">III</o></n><n i="In"><o p="28">P</o></n><n i="Io"><o p="29">I</o><o p="30">1</o></n><n i="Ip"><o p="31">B</o></n><n i="Iq"><o p="32">LI</o></n><n i="Ir"><o p="34">S</o></n><n i="Is"><o p="35">H</o></n><n i="It"><o p="36">F</o></n><n i="Iu"><o p="37">T</o></n><n i="Iv"><o p="38">E</o></n><n i="Iw"><o p="39">V</o></n><n i="Ix"><o p="40">ERY</o><o p="43">erv</o></n><n i="Iz"><o p="46">fl</o></n><n i="TA"><o p="48">I</o><o p="49">1</o></n><n i="I0"><o p="50">R</o></n><n i="I1"><o p="51">D</o></n><n i="I2"><o p="52">A</o></n><n i="I3"><o p="53">Y</o></n></nodes></zone></article-element></article-clipping></article-page></article>

=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article-segmented/batch_deseret_news/articles/8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article SYSTEM "article.dtd">
<article xmlns="http://www.iarchives.com/schema/2002/export" unit-href="../unit.xml" classification="advertising"><header-item name="volume" value="1">I</header-item><header-item name="number" value="1">1</header-item><header-item name="date" value="675867">15-JUN-1850</header-item><header-item name="page" value="4">4</header-item><article-page href="../pages/p004_Va_071_D45_v01.xml"><article-clipping image-file="pdf/8.pdf" index="0" l="0" t="1722" r="498" b="1962"><article-element type="article"><zone l="0" t="0" r="498" b="240"><nodes><n i="K0"><o p="0">1</o></n><n i="K1"><o p="1">wasted</o><o p="7">WAITED</o></n><n i="K2"><o p="13">at</o></n><n i="K3"><o p="15">our</o></n><n i="FW"><o p="18">office</o></n><n i="K4"><o p="24">oali</o></n><n i="K5"><o p="28">ce</o></n><n i="FX"><o p="30">gour</o><o p="34">hour</o></n><n i="FY"><o p="38">wheat</o></n><n i="FZ"><o p="43">V</o></n><n i="Fb"><o p="44">heat</o></n><n i="Fa"><o p="48">corn</o><o p="52">corll</o></n><n i="Fc"><o p="57">meal</o><o p="61">ineal</o></n><n i="Fd"><o p="66">butter</o></n><n i="Fe"><o p="72">cheese</o></n><n i="Ff"><o p="78">1</o></n><n i="Fg"><o p="79">low</o><o p="82">dow</o></n><n i="Fh"><o p="85">and</o></n><n i="Fi"><o p="88">pork</o></n><n i="Fj"><o p="92">in</o></n><n i="Fk"><o p="94">exchange</o></n><n i="Fl"><o p="102">for</o></n><n i="Fm"><o p="105">llie</o><o p="109">tile</o></n><n i="Fn"><o p="113">nas</o><o p="116">fas</o></n></nodes></zone></article-element></article-clipping><article-clipping image-file="pdf/8.pdf" index="1" l="497" t="0" r="926" b="730"><article-element type="article"><zone l="0" t="0" r="429" b="730"><nodes><n i="Tw"><o p="0">ja</o></n><n i="FS"><o p="2">I</o><o p="3">1</o></n><n i="K7"><o p="4">we</o></n><n i="K9"><o p="6">home</o><o p="10">homo</o></n><n i="K+"><o p="14">affairs</o></n><n i="K/"><o p="21">this</o></n><n i="LA"><o p="25">week</o></n><n i="LB"><o p="29">to</o></n><n i="CC"><o p="31">case</o><o p="35">ease</o></n><n i="Sl"><o p="39">tv</o></n><n i="LC"><o p="41">cave</o></n><n i="Sm"><o p="45">ve</o></n><n i="LD"><o p="47">ruc</o><o p="50">rul</o></n><n i="LE"><o p="53">in</o></n><n i="LF"><o p="55">i</o></n><n i="LG"><o p="56">i</o></n><n i="LH"><o p="57">foreign</o></n><n i="LJ"><o p="64">pk</o></n><n i="LL"><o p="66">etche</o></n><n i="LK"><o p="71">ot</o></n><n i="LM"><o p="73">which</o></n><n i="LN"><o p="78">vc</o><o p="80">we</o></n><n i="LO"><o p="82">cil</o><o p="85">cli</o></n><n i="LP"><o p="88">give</o></n><n i="LQ"><o p="92">but</o></n><n i="LR"><o p="95">few</o></n><n i="LS"><o p="98">fires</o></n><n i="LT"><o p="103">and</o></n><n i="C2"><o p="106">flo</o><o p="109">fio</o></n><n i="LU"><o p="112">lloyds</o><o p="118">flocia</o></n><n i="C3"><o p="124">cIs</o></n><n i="C4"><o p="127">murders</o></n><n i="C5"><o p="134">a</o></n><n i="C6"><o p="135">id</o></n><n i="So"><o p="137">rr</o></n><n i="C7"><o p="139">rol</o><o p="142">roi</o></n><n i="C8"><o p="145">berils</o></n><n i="LV"><o p="151">cholera</o></n><n i="LW"><o p="158">and</o></n><n i="LX"><o p="161">perplex</o></n><n i="LY"><o p="168">lcy</o><o p="171">icy</o></n><n i="LZ"><o p="174">of</o></n><n i="La"><o p="176">lotions</o></n><n i="Lb"><o p="183">are</o><o p="186">arc</o></n><n i="Lc"><o p="189">prevalent</o></n><n i="Le"><o p="198">con</o><o p="201">cou</o></n><n i="Lf"><o p="204">bernoi</o></n><n i="Sq"><o p="210">ZD</o></n><n i="Lh"><o p="212">which</o></n><n i="Li"><o p="217">we</o></n><n i="Lj"><o p="219">shall</o><o p="224">shail</o></n><n i="Lk"><o p="229">continue</o></n><n i="Ll"><o p="237">to</o></n><n i="Ln"><o p="239">sketch</o></n><n i="Lo"><o p="245">cli</o><o p="248">cil</o></n><n i="Lq"><o p="251">from</o></n><n i="Lr"><o p="255">the</o></n><n i="Ls"><o p="258">best</o></n><n i="Lt"><o p="262">information</o></n><n i="Lu"><o p="274">yet</o></n><n i="Lv"><o p="277">obtained</o></n><n i="Lw"><o p="285">it</o></n><n i="Lx"><o p="287">is</o></n><n i="Ly"><o p="289">believed</o></n><n i="Lz"><o p="297">that</o><o p="301">fluit</o></n><n i="L0"><o p="306">til</o><o p="309">tib</o></n><n i="L1"><o p="312">house</o></n><n i="L2"><o p="317">wa</o></n><n i="L3"><o p="319">i</o></n><n i="Bv"><o p="320">I</o><o p="321">1</o></n><n i="Bw"><o p="322">cu</o></n><n i="L4"><o p="324">ill</o><o p="327">iii</o></n><n i="C"><o p="330">uve</o><o p="333">the</o></n><n i="E"><o p="336">wee</o><o p="339">woe</o></n><n i="D"><o p="342">acks</o></n><n i="G"><o p="346">n</o></n><n i="I"><o p="347">s</o></n><n i="F"><o p="348">in</o><o p="350">ju</o></n><n i="H"><o p="352">cleetta</o></n><n i="J"><o p="359">a</o></n><n i="K"><o p="360">S</o></n><n i="L"><o p="361">ealier</o></n><n i="M"><o p="367">and</o><o p="370">aud</o></n><n i="N"><o p="373">clerk</o></n><n i="O"><o p="378">and</o></n><n i="P"><o p="381">their</o></n><n i="W"><o p="386">p</o></n><n i="Q"><o p="387">progress</o></n><n i="Y"><o p="395">n</o></n><n i="S"><o p="396">s</o></n><n i="R"><o p="397">since</o></n><n i="U"><o p="402">ice</o></n><n i="T"><o p="405">lias</o><o p="409">has</o></n><n i="V"><o p="412">well</o><o p="416">weil</o></n><n i="X"><o p="420">compared</o></n><n i="b"><o p="428">has</o></n><n i="d"><o p="431">again</o></n><n i="e"><o p="436">appeared</o></n><n i="f"><o p="444">m</o></n><n i="Ss"><o p="445">in</o></n><n i="g"><o p="447">the</o></n><n i="h"><o p="450">states</o><o p="456">stakes</o></n><n i="i"><o p="462">hungary</o></n><n i="j"><o p="469">has</o></n><n i="k"><o p="472">fallen</o></n><n i="m"><o p="478">n</o></n><n i="n"><o p="479">i</o></n><n i="o"><o p="480">en</o><o p="482">bit</o></n><n i="p"><o p="485">rope</o></n><n i="L5"><o p="489">and</o></n><n i="L6"><o p="492">tile</o><o p="496">che</o></n><n i="L7"><o p="499">present</o></n><n i="L9"><o p="506">is</o></n><n i="L+"><o p="508">like</o></n><n i="L/"><o p="512">a</o></n><n i="MA"><o p="513">calm</o></n><n i="MB"><o p="517">before</o></n><n i="MD"><o p="523">a</o></n><n i="ME"><o p="524">more</o></n><n i="MG"><o p="528">hereafter</o></n><n i="MH"><o p="537">rcy</o><o p="540">0</o></n><n i="MI"><o p="541">post</o></n><n i="MJ"><o p="545">africo</o></n><n i="ML"><o p="551">ope</o><o p="554">opet</o></n><n i="TV"><o p="558">fach</o></n><n i="Tr"><o p="562">tach</o></n><n i="MN"><o p="566">ch</o></n><n i="MM"><o p="568">sabbath</o></n><n i="MO"><o p="576">chwi</o></n><n i="St"><o p="580">om</o></n><n i="MP"><o p="582">12</o></n><n i="MQ"><o p="584">to</o></n><n i="MR"><o p="586">1</o></n><n i="FV"><o p="587">alel</o></n><n i="MT"><o p="591">P</o></n><n i="MU"><o p="592">BT</o></n></nodes></zone></article-element></article-clipping></article-page></article>

=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article-segmented/batch_deseret_news/articles/16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article SYSTEM "article.dtd">
<article xmlns="http://www.iarchives.com/schema/2002/export" unit-href="../unit.xml" classification="article"><header-item name="volume" value="1">I</header-item><header-item name="number" value="1">1</header-item><header-item name="date" value="675867">15-JUN-1850</header-item><header-item name="page" value="8">8</header-item><header-item name="headline">Poetry</header-item><article-page href="../pages/p008_Va_071_D45_v01.xml"><article-clipping image-file="pdf/16.pdf" index="0" l="501" t="0" r="934" b="481"><article-element type="headline"><text>Poetry </text></article-element><article-element type="subheadline"><text>To My Friends in the Valley </text></article-element><article-element type="article"><zone l="0" t="0" r="433" b="481"><nodes><n i="Vm"><o p="0">tO</o></n><n i="Vn"><o p="2">ETRY</o></n><n i="Tb"><o p="6">to</o></n><n i="Tc"><o p="8">MY</o></n><n i="Tf"><o p="10">v</o></n><n i="Te"><o p="11">is</o><o p="13">vi</o></n><n i="Th"><o p="15">i</o></n><n i="Tg"><o p="16">ane</o></n><n i="Ti"><o p="19">VALLEY</o></n><n i="Tj"><o p="25">let</o></n><n i="Tk"><o p="28">all</o></n><n i="Tl"><o p="31">who</o></n><n i="Tm"><o p="34">would</o></n><n i="Tn"><o p="39">have</o></n><n i="To"><o p="43">a</o></n><n i="Tp"><o p="44">good</o></n><n i="Tq"><o p="48">paper</o></n><n i="Tr"><o p="53">their</o></n><n i="Ts"><o p="58">talents</o></n><n i="Tt"><o p="65">and</o></n><n i="Tu"><o p="68">time</o></n><n i="Tv"><o p="72">nee</o><o p="75">neer</o></n><n i="Tw"><o p="79">abuse</o></n><n i="Tx"><o p="84">since</o></n><n i="CQ"><o p="89">said</o><o p="93">sald</o></n><n i="Tz"><o p="97">maidby</o></n><n i="CR"><o p="103">by</o></n><n i="CS"><o p="105">the</o></n><n i="CT"><o p="108">wise</o></n><n i="T1"><o p="112">and</o></n><n i="T2"><o p="115">the</o></n><n i="T3"><o p="118">humor</o><o p="123">humored</o></n><n i="UC"><o p="130">cd</o></n><n i="T4"><o p="132">that</o></n><n i="T5"><o p="136">the</o></n><n i="T6"><o p="139">best</o></n><n i="T7"><o p="143">in</o></n><n i="T8"><o p="145">the</o></n><n i="T9"><o p="148">world</o></n><n i="T+"><o p="153">is</o></n><n i="T/"><o p="155">the</o></n><n i="UA"><o p="158">NEWS</o></n><n i="IB"><o p="162">then</o></n><n i="IC"><o p="166">ye</o></n><n i="ID"><o p="168">who</o></n><n i="IE"><o p="171">so</o></n><n i="IF"><o p="173">long</o></n><n i="IG"><o p="177">have</o></n><n i="IH"><o p="181">been</o></n><n i="II"><o p="185">thinking</o></n><n i="IJ"><o p="193">what</o></n><n i="IK"><o p="197">paper</o></n><n i="IL"><o p="202">this</o></n><n i="IM"><o p="206">year</o></n><n i="IN"><o p="210">you</o></n><n i="IO"><o p="213">will</o></n><n i="IP"><o p="217">choose</o></n><n i="IQ"><o p="223">come</o></n><n i="IR"><o p="227">trip</o></n><n i="IS"><o p="231">gaily</o></n><n i="IT"><o p="236">up</o></n><n i="IU"><o p="238">to</o></n><n i="IV"><o p="240">the</o></n><n i="IW"><o p="243">office</o></n><n i="IX"><o p="249">and</o></n><n i="IY"><o p="252">subscribe</o></n><n i="IZ"><o p="261">for</o></n><n i="Ia"><o p="264">the</o></n><n i="Ib"><o p="267">DESERET</o></n><n i="Ic"><o p="274">NEWS</o></n><n i="Id"><o p="278">and</o></n><n i="Ie"><o p="281">now</o></n><n i="If"><o p="284">dearest</o></n><n i="Ig"><o p="291">friends</o></n><n i="Ih"><o p="298">I</o><o p="299">1</o></n><n i="Ii"><o p="300">will</o></n><n i="Ij"><o p="304">leave</o><o p="309">leate</o></n><n i="Ik"><o p="314">you</o></n><n i="Il"><o p="317">this</o></n><n i="Im"><o p="321">counsel</o></n><n i="In"><o p="328">I</o><o p="329">1</o></n><n i="Io"><o p="330">pray</o></n><n i="Ip"><o p="334">you</o></n><n i="Iq"><o p="337">dont</o></n><n i="H"><o p="341">ose</o><o p="344">iose</o></n><n i="Is"><o p="348">the</o></n><n i="It"><o p="351">best</o></n><n i="Iu"><o p="355">of</o></n><n i="Iv"><o p="357">advice</o></n><n i="Iw"><o p="363">I</o><o p="364">1</o></n><n i="Ix"><o p="365">can</o></n><n i="Iy"><o p="368">give</o></n><n i="Iz"><o p="372">you</o></n><n i="BO"><o p="375">I</o><o p="376">1</o></n><n i="I0"><o p="377">Is</o></n><n i="I1"><o p="379">pay</o></n><n i="I2"><o p="382">in</o></n><n i="I3"><o p="384">advance</o></n><n i="I4"><o p="391">for</o></n><n i="I5"><o p="394">the</o><o p="397">thea</o></n><n i="Bj"><o p="401">sew</o></n><n i="I6"><o p="404">new</o></n><n i="I7"><o p="407">B</o></n></nodes></zone></article-element></article-clipping></article-page></article>

=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article-segmented/batch_desnews/articles/7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article SYSTEM "article.dtd">
<article xmlns="http://www.iarchives.com/schema/2002/export" unit-href="../unit.xml" classification="article"><header-item name="volume" value="1">I</header-item><header-item name="number" value="1">1</header-item><header-item name="date" value="675867">15-JUN-1850</header-item><header-item name="page" value="4">4</header-item><header-item name="headline">Office of Delivery</header-item><article-page href="../pages/p004_Va_071_D45_v01.xml"><article-clipping image-file="pdf/7.pdf" index="0" l="0" t="1001" r="498" b="1724"><article-element type="headline"><text>Office of Delivery </text></article-element><article-element type="article"><zone l="0" t="0" r="498" b="723"><nodes><n i="C/"><o p="0">aj</o></n><n i="I4"><o p="2">OFFICE</o></n><n i="I5"><o p="8">or</o><o p="10">OF</o></n><n i="I7"><o p="12">the</o></n><n i="Su"><o p="15">J</o></n><n i="I8"><o p="16">news</o></n><n i="I9"><o p="20">will</o></n><n i="I+"><o p="24">bp</o><o p="26">be</o></n><n i="I/"><o p="28">delivered</o></n><n i="JA"><o p="37">at</o></n><n i="JB"><o p="39">the</o></n><n i="JC"><o p="42">post</o></n><n i="JD"><o p="46">offic</o></n><n i="JE"><o p="51">subscribers</o></n><n i="Fo"><o p="62">brorn</o></n><n i="JF"><o p="67">1</o></n><n i="JG"><o p="68">born</o></n><n i="JH"><o p="72">distant</o></n><n i="JI"><o p="79">parts</o></n><n i="JJ"><o p="84">of</o></n><n i="JK"><o p="86">the</o></n><n i="JL"><o p="89">valley</o></n><n i="JM"><o p="95">to</o></n><n i="JN"><o p="97">order</o></n><n i="JO"><o p="102">but</o><o p="105">hut</o></n><n i="JP"><o p="108">for</o></n><n i="JQ"><o p="111">their</o></n><n i="JR"><o p="116">convenience</o></n><n i="JS"><o p="127">we</o></n><n i="JT"><o p="129">propose</o></n><n i="JU"><o p="137">to</o></n><n i="JV"><o p="139">forward</o></n><n i="JW"><o p="146">packages</o></n><n i="JX"><o p="154">as</o></n><n i="JY"><o p="156">we</o></n><n i="JZ"><o p="158">may</o></n><n i="Ja"><o p="161">have</o></n><n i="Sv"><o p="165">tr</o></n><n i="Jb"><o p="167">opportunity</o></n><n i="Jc"><o p="178">to</o></n><n i="Sx"><o p="180">A</o></n><n i="Jd"><o p="181">ANSON</o></n><n i="Tn"><o p="186">sos</o></n><n i="Sy"><o p="189">sov</o></n><n i="Je"><o p="192">CALL</o></n><n i="Jf"><o p="196">north</o></n><n i="Jg"><o p="201">kanyon</o></n><n i="Jh"><o p="207">ward</o></n><n i="Ji"><o p="211">DANIEL</o></n><n i="Jj"><o p="217">millen</o><o p="223">MILLER</o></n><n i="Jk"><o p="229">north</o></n><n i="Jl"><o p="234">cottonwood</o></n><n i="Tc"><o p="245">W</o></n><n i="Ft"><o p="246">dad</o><o p="249">uld</o></n><n i="Jm"><o p="252">ISAAC</o></n><n i="Jn"><o p="257">CLARK</o></n><n i="Jo"><o p="262">brownsville</o></n><n i="Jp"><o p="273">Browns</o></n><n i="Jr"><o p="279">ville</o></n><n i="Jq"><o p="284">JOEL</o></n><n i="Js"><o p="288">JOHNSON</o></n><n i="Jt"><o p="295">mill</o></n><n i="Ju"><o p="299">creek</o></n><n i="Jv"><o p="304">WILLIAM</o><o p="312">WILLIAU</o></n><n i="Jw"><o p="320">CROSBY</o></n><n i="Jx"><o p="326">cottonwood</o></n><n i="Jy"><o p="336">ISAAC</o></n><n i="J0"><o p="341">Hi</o></n><n i="Jz"><o p="343">HIGBEE</o></n><n i="J2"><o p="349">GurE</o></n><n i="J1"><o p="353">utah</o></n><n i="J3"><o p="357">valley</o></n><n i="J4"><o p="363">PHINEAS</o></n><n i="J5"><o p="370">richards</o></n><n i="J6"><o p="378">san</o></n><n i="J7"><o p="381">pete</o></n><n i="J8"><o p="385">valley</o></n><n i="J9"><o p="391">EZRA</o></n><n i="J+"><o p="396">T</o></n><n i="J/"><o p="397">besson</o><o p="403">BENSON</o></n><n i="Sz"><o p="409">BE</o></n><n i="q"><o p="411">ason</o><o p="415">lson</o></n><n i="KA"><o p="419">tooele</o><o p="425">thoele</o></n><n i="KB"><o p="431">valley</o></n><n i="KC"><o p="437">and</o></n><n i="Te"><o p="440">rc</o></n><n i="KD"><o p="442">request</o></n><n i="Tf"><o p="449">kuest</o></n><n i="KE"><o p="454">them</o></n><n i="KF"><o p="458">to</o></n><n i="KG"><o p="460">act</o></n><n i="KH"><o p="463">as</o></n><n i="KI"><o p="465">our</o></n><n i="KJ"><o p="468">agents</o></n><n i="KK"><o p="474">subscribers</o></n><n i="S2"><o p="485">bers</o></n><n i="KL"><o p="489">will</o></n><n i="KM"><o p="493">do</o></n><n i="KN"><o p="495">well</o></n><n i="KO"><o p="499">to</o></n><n i="KP"><o p="501">inform</o></n><n i="KQ"><o p="507">us</o></n><n i="KR"><o p="509">or</o></n><n i="KS"><o p="511">the</o><o p="514">tiie</o></n><n i="KT"><o p="518">above</o></n><n i="KU"><o p="523">agent</o><o p="528">agents</o></n><n i="KV"><o p="534">s</o></n><n i="Tv"><o p="535">chere</o></n><n i="KX"><o p="540">they</o></n><n i="KY"><o p="544">will</o></n><n i="KZ"><o p="548">receive</o></n><n i="Ka"><o p="555">their</o></n><n i="Kb"><o p="560">papers</o></n><n i="Kc"><o p="566">city</o></n><n i="Kd"><o p="570">subscribers</o></n><n i="Ke"><o p="581">call</o><o p="585">can</o></n><n i="Kf"><o p="588">have</o></n><n i="Kg"><o p="592">their</o></n><n i="Kh"><o p="597">papers</o></n><n i="Ki"><o p="603">delivered</o></n><n i="Kj"><o p="612">for</o></n><n i="Kk"><o p="615">ail</o><o p="618">an</o></n><n i="Kl"><o p="620">additional</o></n><n i="Km"><o p="630">50</o></n><n i="Kn"><o p="632">cents</o></n><n i="Ko"><o p="637">for</o></n><n i="Kp"><o p="640">the</o></n><n i="Kq"><o p="643">term</o></n><n i="Kr"><o p="647">provided</o></n><n i="Ks"><o p="655">0</o></n><n i="Kt"><o p="656">ough</o></n><n i="Ku"><o p="660">wish</o></n><n i="Kv"><o p="664">it</o></n><n i="Kw"><o p="666">to</o></n><n i="Kx"><o p="668">employ</o></n><n i="Ky"><o p="674">a</o></n><n i="Kz"><o p="675">carrier</o></n></nodes></zone></article-element></article-clipping></article-page></article>
