=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article_segmented/batch_deseret_news/unit.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Russell Black (iArchives) -->
<!--DTD generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<!--For a unit, these are all the articles contained in this unit.  For a page, these are all the articles which *begin* on the page.-->
<!ELEMENT articles (article-ref*)>
<!--This is the meta-data associated with the scope.  It might include date, edition, section,  page, article name, etc.-->
<!ELEMENT header-item (#PCDATA)>
<!--name: The type of data contained in the element (date, edition, section)-->
<!ATTLIST header-item
	name CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!--A sequence of word nodes-->
<!ELEMENT nodes (n*)>
<!--Represents a unit such as a newspaper issue or a book-->
<!ELEMENT unit (header-item*, pages, articles?)>
<!--collection-title: The title of the collection to which the unit belongs.  For newspapers, this is the name of the newspaper, for a collection of books, it's the title of the collection.  Note: the book title will be contained in the first header-item.  -->
<!ATTLIST unit
	collection-title CDATA #REQUIRED
	xmlns CDATA #FIXED "http://www.iarchives.com/schema/2002/export"
>
<!--A reference to an article-->
<!ELEMENT article-ref EMPTY>
<!--href: A relative path to the xml describing this article-->
<!ATTLIST article-ref
	href CDATA #REQUIRED
>
<!--Node Element.  Represents one or more word options at a given location.  Element and attribute names are abbreviated to save space, since there will be many of these elements.-->
<!ELEMENT n (r*, o+)>
<!--i: the node's ID.  Note that these ID's are not global.  They are local to the enclosing nodes element.-->
<!--n: A comma-separated list of next-node IDs.  The OCR tries to order the words in reading order, and this is the way that is represented.  Multiple next-nodes occur when multiple OCR engines disagree on which word should follow.  -->
<!ATTLIST n
	i CDATA #REQUIRED
	n CDATA #IMPLIED
>
<!--All the pages contained in this unit-->
<!ELEMENT pages (page-ref+)>
<!--Node rectangle.  Nodes may have more than one rectangle ( if the word is hyphenated, for example).  If the exported images is PDF only, word coordinates are not needed, and there will be no rectangle node.-->
<!ELEMENT r EMPTY>
<!--l: The left coordinate-->
<!--t: The top coordinate-->
<!--r: The right coordinate-->
<!--b: The bottom coordinate-->
<!ATTLIST r
	l CDATA #REQUIRED
	t CDATA #REQUIRED
	r CDATA #REQUIRED
	b CDATA #REQUIRED
>
<!--Word option element.  The text of this element is the word.-->
<!ELEMENT o (#PCDATA)>
<!--p: The pdf character offset
This is the character offset that marks the beginning of the word on the corresponding pdf page.  It facilitates pdf word highlighting, and corresponds to the "pos" attribute in the pdf Highlight Format's "loc" tag.-->
<!ATTLIST o
	p CDATA #IMPLIED
>
<!--A reference to a page-->
<!ELEMENT page-ref EMPTY>
<!--href: A relative path to the xml describing this page-->
<!ATTLIST page-ref
	href CDATA #REQUIRED
>

=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article_segmented/batch_deseret_news/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE unit SYSTEM "unit.dtd">
<unit xmlns="http://www.iarchives.com/schema/2002/export" collection-title="Untitled"><header-item name="volume" value="1">I</header-item><header-item name="number" value="1">1</header-item><header-item name="date" value="675867">15-JUN-1850</header-item><pages><page-ref href="pages/p001_Va_071_D45_v01.xml" /><page-ref href="pages/p002_Va_071_D45_v01.xml" /><page-ref href="pages/p003_Va_071_D45_v01.xml" /><page-ref href="pages/p004_Va_071_D45_v01.xml" /><page-ref href="pages/p005_Va_071_D45_v01.xml" /><page-ref href="pages/p006_Va_071_D45_v01.xml" /><page-ref href="pages/p007_Va_071_D45_v01.xml" /><page-ref href="pages/p008_Va_071_D45_v01.xml" /></pages><articles><article-ref href="articles/0.xml" /><article-ref href="articles/1.xml" /><article-ref href="articles/2.xml" /><article-ref href="articles/3.xml" /><article-ref href="articles/4.xml" /><article-ref href="articles/5.xml" /><article-ref href="articles/6.xml" /><article-ref href="articles/7.xml" /><article-ref href="articles/8.xml" /><article-ref href="articles/9.xml" /><article-ref href="articles/10.xml" /><article-ref href="articles/11.xml" /><article-ref href="articles/12.xml" /><article-ref href="articles/13.xml" /><article-ref href="articles/14.xml" /><article-ref href="articles/15.xml" /><article-ref href="articles/16.xml" /><article-ref href="articles/17.xml" /></articles></unit>
