=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article_segmented/batch_topaz_times/pages/page.dtd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by blank (blank) --><!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><!ELEMENT articles (article-ref*)><!ELEMENT header-item (#PCDATA)><!ATTLIST header-item	name CDATA #REQUIRED	value CDATA #IMPLIED	xmlns CDATA #FIXED "http://www.iarchives.com/schema/2002/export"><!ELEMENT nodes (n*)><!ELEMENT page (header-item*, articles?, nodes?)><!ATTLIST page	unit-href CDATA #REQUIRED	image-file CDATA #REQUIRED	predicted-word-accuracy CDATA #IMPLIED><!ELEMENT article-ref EMPTY><!ATTLIST article-ref	href CDATA #REQUIRED><!ELEMENT n (r*, o+)><!ATTLIST n	i CDATA #REQUIRED	n CDATA #IMPLIED><!ELEMENT r EMPTY><!ATTLIST r	l CDATA #REQUIRED	t CDATA #REQUIRED	r CDATA #REQUIRED	b CDATA #REQUIRED><!ELEMENT o (#PCDATA)><!ATTLIST o	p CDATA #IMPLIED	c CDATA #IMPLIED	f CDATA #IMPLIED>

=== marriott-library/newspaper_works_fixtures/spec/fixtures/files/article-segmented/batch_desnews/pages/p002_Va_071_D45_v01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "page.dtd">
<page xmlns="http://www.iarchives.com/schema/2002/export" unit-href="../unit.xml" image-file="pdf/p002_Va_071_D45_v01.pdf"><header-item name="volume" value="1">I</header-item><header-item name="number" value="1">1</header-item><header-item name="date" value="675867">15-JUN-1850</header-item><header-item name="page" value="2">2</header-item><articles><article-ref href="../articles/4.xml" /></articles><nodes><n i="kd"><o p="0">ir</o></n><n i="K6"><o p="2">ira</o></n><n i="qy"><o p="5">lra</o></n><n i="K7"><o p="8">j</o></n><n i="G5"><o p="9">til</o></n><n i="ke"><o p="12">j</o></n><n i="kf"><o p="13">MESS</o></n><n i="kg"><o p="17">1</o></n><n i="K9"><o p="18">hou</o></n><n i="K+"><o p="21">of</o></n><n i="rn"><o p="23">noo</o></n><n i="K/"><o p="26">0</o></n><n i="G6"><o p="27">tag</o></n><n i="ki"><o p="30">th</o></n><n i="LA"><o p="32">T</o></n><n i="y"><o p="33">I</o><o p="34">1</o></n><n i="kj"><o p="35">b</o></n><n i="LE"><o p="36">trim</o></n><n i="kk"><o p="40">in</o></n><n i="kl"><o p="42">4</o></n><n i="km"><o p="43">nit</o></n><n i="Fo"><o p="46">I</o><o p="47">1</o></n><n i="kn"><o p="48">it</o></n><n i="LB"><o p="50">i</o></n><n i="LC"><o p="51">i</o></n><n i="Fp"><o p="52">it</o><o p="54">tt</o></n><n i="ko"><o p="56">v</o></n><n i="kp"><o p="57">it</o></n><n i="LD"><o p="59">t</o></n><n i="LG"><o p="60">i</o></n><n i="kq"><o p="61">wr</o></n><n i="LH"><o p="63">to</o></n><n i="LI"><o p="65">i</o></n><n i="LJ"><o p="66">i</o></n><n i="kr"><o p="67">ij</o></n><n i="LT"><o p="69">1</o></n><n i="LS"><o p="70">l</o></n><n i="K"><o p="71">rila</o><o p="75">tiia</o></n><n i="CX"><o p="79">ably</o></n><n i="LK"><o p="83">1</o></n><n i="Ih"><o p="84">eist</o><o p="88">elst</o></n><n i="ks"><o p="92">of</o></n><n i="kt"><o p="94">AW</o></n><n i="ku"><o p="96">i</o></n><n i="LU"><o p="97">un</o></n><n i="E"><o p="99">are</o><o p="102">arr</o></n><n i="sB"><o p="105">aply</o></n><n i="n5"><o p="109">i</o></n><n i="qz"><o p="110">rip</o></n><n i="n6"><o p="113">ip</o></n><n i="LM"><o p="115">ir</o></n><n i="LN"><o p="117">t</o></n><n i="kv"><o p="118">of</o></n><n i="LO"><o p="120">0</o></n><n i="LP"><o p="121">h</o></n><n i="kw"><o p="122">4</o></n><n i="LQ"><o p="123">iu</o></n><n i="kx"><o p="125">1</o></n><n i="LV"><o p="126">ii</o></n><n i="ky"><o p="128">1</o></n><n i="LW"><o p="129">pir</o></n><n i="CZ"><o p="132">arois</o></n><n i="LX"><o p="137">which</o></n><n i="LR"><o p="142">i</o></n><n i="F"><o p="143">ill</o><o p="146">III</o></n><n i="B2"><o p="149">th</o><o p="151">tit</o></n><n i="k1"><o p="154">0</o></n><n i="DU"><o p="155">I</o><o p="156">1</o></n><n i="n7"><o p="157">lr</o></n><n i="k0"><o p="159">rm</o></n><n i="DO"><o p="161">mation</o><o p="167">aaion</o></n><n i="Fr"><o p="172">ill</o><o p="175">iu</o></n><n i="h"><o p="177">the</o><o p="180">cie</o></n><n i="k2"><o p="183">n</o></n><n i="k3"><o p="184">of</o></n><n i="LY"><o p="186">jl</o></n><n i="Ii"><o p="188">tins</o><o p="192">thi</o></n><n i="La"><o p="195">asked</o></n><n i="Lb"><o p="200">forby</o></n><n i="Lc"><o p="205">the</o></n><n i="Ld"><o p="208">r</o></n><n i="Le"><o p="209">v</o></n><n i="Lf"><o p="210">on</o></n><n i="Lg"><o p="212">c</o></n><n i="JX"><o p="213">hinline</o><o p="220">inline</o></n><n i="Ks"><o p="226">rnino</o></n><n i="Lh"><o p="231">in</o></n><n i="Li"><o p="233">3</o></n><n i="k4"><o p="234">office</o></n><n i="DV"><o p="240">I</o><o p="241">1</o></n><n i="Ca"><o p="242">faund</o></n><n i="Lj"><o p="247">th</o></n><n i="Lk"><o p="249">military</o></n><n i="k5"><o p="257">vm</o></n><n i="Ll"><o p="259">r</o></n><n i="q0"><o p="260">irn</o></n><n i="Ft"><o p="263">TI</o><o p="265">a</o></n><n i="Fu"><o p="266">I</o><o p="267">1</o></n><n i="Cb"><o p="268">idiart</o></n><n i="k6"><o p="274">of</o></n><n i="Lm"><o p="276">if</o></n><n i="3"><o p="278">the</o><o p="281">die</o></n><n i="qT"><o p="284">dep</o></n><n i="K3"><o p="287">ament</o></n><n i="Lo"><o p="292">of</o></n><n i="Lp"><o p="294">california</o></n><n i="Lq"><o p="304">rt</o></n><n i="qU"><o p="306">i</o></n><n i="rp"><o p="307">lug</o></n><n i="qV"><o p="310">ig</o></n><n i="Lr"><o p="312">thi</o></n><n i="k7"><o p="315">i</o></n><n i="qW"><o p="316">i</o></n><n i="rq"><o p="317">tic</o></n><n i="qX"><o p="320">ic</o></n><n i="Kt"><o p="322">eions</o></n><n i="k8"><o p="327">of</o></n><n i="k9"><o p="329">civil</o></n><n i="Lu"><o p="334">governor</o></n><n i="Lv"><o p="342">in</o></n><n i="Lw"><o p="344">i</o></n><n i="k+"><o p="345">V</o></n><n i="n8"><o p="346">rr</o></n><n i="n9"><o p="348">iton</o></n><n i="k/"><o p="352">a</o></n><n i="DW"><o p="353">1</o></n><n i="lA"><o p="354">i</o></n><n i="Lx"><o p="355">id</o></n><n i="lB"><o p="357">i</o></n><n i="Ly"><o p="358">left</o></n><n i="Fv"><o p="362">ss</o><o p="364">as</o></n><n i="n+"><o p="366">s</o></n><n i="n/"><o p="367">s</o></n><n i="DX"><o p="368">I</o><o p="369">1</o></n><n i="Lz"><o p="370">wis</o></n><n i="lC"><o p="373">w</o></n><n i="lD"><o p="374">ts</o></n><n i="L0"><o p="376">t</o></n><n i="lE"><o p="377">to</o></n><n i="L1"><o p="379">act</o></n><n i="L2"><o p="382">un</o></n><n i="lF"><o p="384">i</o></n><n i="lG"><o p="385">tr</o></n><n i="sf"><o p="387">ltv</o></n><n i="sC"><o p="390">adalae</o></n><n i="oA"><o p="396">ad</o></n><n i="CE"><o p="398">aine</o><o p="402">Alne</o></n><n i="lI"><o p="406">11</o></n><n i="L4"><o p="408">d</o></n><n i="rr"><o p="409">bigo</o></n><n i="q1"><o p="413">1210</o></n><n i="L5"><o p="417">with</o></n><n i="lJ"><o p="421">01</o></n><n i="MN"><o p="423">r</o></n><n i="Ku"><o p="424">aa</o></n><n i="MO"><o p="426">a</o></n><n i="L6"><o p="427">iv</o></n><n i="L7"><o p="429">provision</o></n><n i="MP"><o p="438">1</o></n><n i="JZ"><o p="439">hlll</o><o p="443">kill</o></n><n i="oE"><o p="447">Sl</o></n><n i="oF"><o p="449">ll</o></n><n i="L8"><o p="451">i</o></n><n i="L9"><o p="452">nent</o></n><n i="lK"><o p="456">ent</o></n><n i="L+"><o p="459">in</o></n><n i="lL"><o p="461">it</o></n><n i="q2"><o p="463">hie</o></n><n i="Fy"><o p="466">thit</o><o p="470">hit</o></n><n i="It"><o p="473">rii</o><o p="476">yli</o></n><n i="ni"><o p="479">rit</o></n><n i="MR"><o p="483">1</o></n><n i="MA"><o p="484">t</o></n><n i="qY"><o p="485">di</o></n><n i="o"><o p="487">dialers</o><o p="494">dialer</o></n><n i="JU"><o p="500">sturt</o><o p="505">sturl</o></n><n i="oB"><o p="510">1</o></n><n i="lO"><o p="511">th</o></n><n i="MB"><o p="513">tiit</o></n><n i="lN"><o p="517">it</o></n><n i="B3"><o p="519">arrange</o><o p="526">arranger</o></n><n i="Fz"><o p="534">ii</o><o p="536">0</o></n><n i="lP"><o p="537">id</o></n><n i="MS"><o p="539">dj</o></n><n i="MT"><o p="541">u</o></n><n i="MU"><o p="542">i</o></n><n i="MC"><o p="543">i</o></n><n i="Cc"><o p="544">predel</o></n><n i="MD"><o p="550">sor</o></n><n i="ME"><o p="553">until</o></n><n i="MF"><o p="558">con</o></n><n i="MG"><o p="561">1</o></n><n i="MV"><o p="562">i</o></n><n i="i"><o p="563">iid</o><o p="566">nid</o></n><n i="lR"><o p="569">lid</o></n><n i="MH"><o p="572">n</o></n><n i="JY"><o p="573">action</o></n><n i="MI"><o p="579">n</o></n><n i="G7"><o p="580">mat</o><o p="583">nat</o></n><n i="MJ"><o p="586">subject</o></n><n i="MW"><o p="593">di</o></n><n i="sg"><o p="595">bor</o></n><n i="Cd"><o p="598">faure</o><o p="603">frune</o></n><n i="oC"><o p="608">fr</o></n><n i="oD"><o p="610">ure</o></n><n i="r2"><o p="613">une</o></n><n i="rs"><o p="616">erek</o></n><n i="Kv"><o p="620">aiji</o></n><n i="ML"><o p="624">i</o></n><n i="MM"><o p="625">ti</o></n><n i="lU"><o p="627">tw</o></n><n i="G8"><o p="629">til</o></n><n i="G9"><o p="632">powers</o></n><n i="lV"><o p="638">r</o></n><n i="lW"><o p="639">i</o></n><n i="B4"><o p="640">ill</o><o p="643">tit</o></n><n i="lX"><o p="646">lint</o></n><n i="lZ"><o p="650">1</o></n><n i="lY"><o p="651">I</o></n><n i="la"><o p="652">co</o></n><n i="G+"><o p="654">continued</o></n><n i="oG"><o p="663">con</o></n><n i="F0"><o p="666">I</o><o p="667">1</o></n><n i="oH"><o p="668">linued</o></n><n i="lb"><o p="674">t</o></n><n i="MX"><o p="675">tt</o></n><n i="Mc"><o p="677">ti</o></n><n i="Md"><o p="679">of</o></n><n i="lc"><o p="681">f</o></n><n i="ld"><o p="682">c</o></n><n i="F1"><o p="683">I</o><o p="684">1</o></n><n i="MY"><o p="685">nv</o></n><n i="sD"><o p="687">airas</o></n><n i="le"><o p="692">as</o></n><n i="Ja"><o p="694">ia</o></n><n i="DY"><o p="696">I</o><o p="697">1</o></n><n i="F2"><o p="698">I</o><o p="699">1</o></n><n i="F3"><o p="700">I</o><o p="701">1</o></n><n i="Me"><o p="702">i</o></n><n i="q3"><o p="703">hao</o></n><n i="lf"><o p="706">h</o></n><n i="Mf"><o p="707">han</o></n><n i="lg"><o p="710">ar</o></n><n i="F4"><o p="712">I</o><o p="713">1</o></n><n i="Ma"><o p="714">n</o></n><n i="j"><o p="715">enn</o><o p="718">can</o></n><n i="sh"><o p="721">ila</o></n><n i="li"><o p="724">v</o></n><n i="lj"><o p="725">tv</o></n><n i="Mg"><o p="727">t</o></n><n i="Mh"><o p="728">an</o></n><n i="Mi"><o p="730">1</o></n><n i="lk"><o p="731">i</o></n><n i="Mj"><o p="732">i</o></n><n i="Mb"><o p="733">if</o></n><n i="ll"><o p="735">c</o></n><n i="lm"><o p="736">11</o></n><n i="sE"><o p="738">ilian</o></n><n i="lo"><o p="743">0</o></n><n i="Ml"><o p="744">t</o></n><n i="lp"><o p="745">V</o></n><n i="Mm"><o p="746">t</o></n><n i="lq"><o p="747">se</o></n><n i="lr"><o p="749">ia</o></n><n i="Nh"><o p="751">i</o></n><n i="Ni"><o p="752">a</o></n><n i="Ij"><o p="753">vii</o><o p="756">vit</o></n><n i="Nj"><o p="759">v</o></n><n i="Nk"><o p="760">n</o></n><n i="Mn"><o p="761">i</o></n><n i="Mo"><o p="762">th</o></n><n i="Mp"><o p="764">faithful</o></n><n i="JV"><o p="772">exe</o><o p="775">exo</o></n><n i="G/"><o p="778">execution</o><o p="787">elocution</o></n><n i="qZ"><o p="796">cution</o></n><n i="Mq"><o p="802">of</o></n><n i="Nl"><o p="804">1</o></n><n i="Nm"><o p="805">S</o></n><n i="z"><o p="806">I</o><o p="807">1</o></n><n i="F5"><o p="808">iv</o><o p="810">
